chore: Adds the OAI RAN CU ROCK
canonical/oai-ran-cu-rock pull request #1
Opened 2024-07-29 12:15 UTC by Gmerold

This PR adds the initial version of the OAI RAN CU ROCK.

The version of the ROCK is set to `2.1.1` which doesn't exist in the upstream. This is to indicate that we're temporarily using the code from the `develop` branch (latest release, `2.1.0`, is over 5 months old). There's a `2.2.0` release planned for end of August. Once it's available, we should switch to that release.

2024-07-29 12:28 UTC, gatici commented
We need to add a license file to the repository similar to this one: https://github.com/canonical/sdcore-amf-rock/blob/main/LICENSE

2024-07-30 15:32 UTC, ghislainbourgeois requested changes

2024-07-30 15:32 UTC, ghislainbourgeois commented on CONTRIBUTING.md
> +sudo skopeo --insecure-policy copy oci-archive:oai-ran-cu_2.1.1_amd64.rock docker-daemon:oai-ran-cu:2.1.1
```suggestion
sudo rockcraft.skopeo --insecure-policy copy oci-archive:oai-ran-cu_2.1.1_amd64.rock docker-daemon:oai-ran-cu:2.1.1
```

2024-07-30 15:32 UTC, ghislainbourgeois commented on rockcraft.yaml
> +    source-branch: develop
Don't we want to use a tag for the version specified above?

2024-07-30 15:33 UTC, ghislainbourgeois commented on rockcraft.yaml
> +    source-branch: develop
I failed to read the description, sorry!

2024-08-01 14:22 UTC, ghislainbourgeois approved these changes

2024-08-02 10:56 UTC, merged